version: '3'
services:
  postgres:
    image: postgres:16-alpine
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - postgres_persist:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "objekt_db"
      POSTGRES_USER: "objekt_adm"
      POSTGRES_PASSWORD: "objekt@123"
    restart: unless-stopped
volumes:
  postgres_persist:
    external: false
