name: Builder Image

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/builder-image.yml
      - Dockerfile.builder
  pull_request:
    branches: [master]

env:
  GO_VERSION: 1.22.2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        labels: |
          org.opencontainers.image.title=objekt-builder
          org.opencontainers.image.description="Builder Image used in CI"
        images: |
          ghcr.io/${{ github.repository }}/builder
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Image to GHCR
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.builder
        platforms: ${{ matrix.platform }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: |
          type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
        build-args: |
          GO_VERSION=${{ env.GO_VERSION }}
