name: Go

on:
  push:
    branches: ['**']
    paths:
      - .github/workflows/go.yml
      - '**/*.go'
      - go.mod
      - go.sum
  pull_request:
    branches: ['master']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/upmahq/objekt/builder:latest
      options: --user 1001 --workdir /buildman
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code
      - name: Go Vet
        run: go vet ./...
      - name: Go Tidy
        run: go mod tidy && git diff --exit-code
      - name: Go Mod
        run: go mod download
      - name: Go Mod Verify
        run: go mod verify
      - name: Go Generate
        run: go generate ./... && git diff --exit-code
      - name: Go Build
        run: go build -o /dev/null ./...
