name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git
        run: |-
          dnf install -y git-all
          git config --global user.name "Github Actions Bot"
          git config --global user.email "<>"
          git --version
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code
      - name: Go Vet
        run: go vet ./...
      - name: Go Tidy
        run: go mod tidy && git diff --exit-code
      - name: Go Mod
        run: go mod download
      - name: Go Mod Verify
        run: go mod verify
      - name: Go Generate
        run: go generate ./... && git diff --exit-code
      - name: Go Build
        run: go build -o /dev/null ./...
